/*
 * SPDX-FileCopyrightText: Copyright (c) 2022-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "lists/utilities.hpp"

#include <cudf/column/column.hpp>
#include <cudf/column/column_device_view.cuh>
#include <cudf/column/column_factories.hpp>
#include <cudf/detail/concatenate.hpp>
#include <cudf/detail/copy.hpp>
#include <cudf/detail/row_operator/equality.cuh>
#include <cudf/detail/row_operator/lexicographic.cuh>
#include <cudf/detail/row_operator/preprocessed_table.cuh>
#include <cudf/detail/sorting.hpp>
#include <cudf/detail/structs/utilities.hpp>
#include <cudf/detail/utilities/linked_column.hpp>
#include <cudf/detail/utilities/vector_factories.hpp>
#include <cudf/lists/lists_column_view.hpp>
#include <cudf/null_mask.hpp>
#include <cudf/strings/strings_column_view.hpp>
#include <cudf/strings/utilities.hpp>
#include <cudf/table/table_view.hpp>
#include <cudf/utilities/bit.hpp>
#include <cudf/utilities/memory_resource.hpp>
#include <cudf/utilities/type_checks.hpp>
#include <cudf/utilities/type_dispatcher.hpp>

#include <thrust/iterator/transform_iterator.h>

#include <cuda_runtime_api.h>

#include <algorithm>
#include <array>
#include <climits>
#include <cstdint>
#include <functional>
#include <limits>
#include <numeric>
#include <stdexcept>
#include <vector>

namespace cudf {
namespace detail {
namespace {

/**
 * @brief Removes the offsets of struct column's children
 *
 * @param c The column whose children are to be un-sliced
 * @return Children of `c` with offsets removed
 */
std::vector<column_view> unslice_children(column_view const& c)
{
  if (c.type().id() == type_id::STRUCT) {
    auto child_it = thrust::make_transform_iterator(c.child_begin(), [](auto const& child) {
      return column_view(
        child.type(),
        child.offset() + child.size(),  // This is hacky, we don't know the actual unsliced size but
                                        // it is at least offset + size
        child.head(),
        child.null_mask(),
        child.null_count(),
        0,
        unslice_children(child));
    });
    return {child_it, child_it + c.num_children()};
  }
  return {c.child_begin(), c.child_end()};
};

/**
 * @brief Removes the child column offsets of struct columns in a table.
 *
 * Given a table, this replaces any struct columns with similar struct columns that have their
 * offsets removed from their children. Structs that are children of list columns are not affected.
 *
 */
table_view remove_struct_child_offsets(table_view table)
{
  std::vector<column_view> cols;
  cols.reserve(table.num_columns());
  std::transform(table.begin(), table.end(), std::back_inserter(cols), [&](column_view const& c) {
    return column_view(c.type(),
                       c.size(),
                       c.head<uint8_t>(),
                       c.null_mask(),
                       c.null_count(),
                       c.offset(),
                       unslice_children(c));
  });
  return table_view(cols);
}

/**
 * @brief The enum to specify whether the `decompose_structs` function will process lists columns
 * (at any nested level) or will output them unchanged.
 */
enum class decompose_lists_column : bool { YES, NO };

/**
 * @brief Decompose all struct columns in a table
 *
 * If a structs column is a tree with N leaves, then this function decomposes the tree into
 * N "linear trees" (branch factor == 1) and prunes common parents. Also returns a vector of
 * per-column `depth`s.
 *
 * A `depth` value is the number of nested levels as parent of the column in the original,
 * non-decomposed table, which are pruned during decomposition.
 *
 * Special handling is needed in the cases of structs column having lists as its first child. In
 * such situations, the function decomposes the tree of N leaves into N+1 linear trees in which the
 * second tree was generated by extracting out leaf of the first tree. This is to make sure there is
 * no structs column having child lists column in the output. Note that structs with lists children
 * in subsequent positions do not require any special treatment because the struct parent will be
 * pruned for all subsequent children.
 *
 * For example, if the original table has a column `Struct<Struct<int, float>, decimal>`,
 *
 *      S1
 *     / \
 *    S2  d
 *   / \
 *  i   f
 *
 * then after decomposition, we get three columns:
 * `Struct<Struct<int>>`, `float`, and `decimal`.
 *
 *  0   2   1  <- depths
 *  S1
 *  |
 *  S2      d
 *  |
 *  i   f
 *
 * The depth of the first column is 0 because it contains all its parent levels, while the depth
 * of the second column is 2 because two of its parent struct levels were pruned.
 *
 * Similarly, a struct column of type `Struct<int, Struct<float, decimal>>` is decomposed as follows
 *
 *     S1
 *    / \
 *   i   S2
 *      / \
 *     f   d
 *
 *  0   1   2  <- depths
 *  S1  S2  d
 *  |   |
 *  i   f
 *
 * In the case of structs column with a lists column as its first child such as
 * `Struct<List<int>, float>`, after decomposition we get three columns `Struct<>`,
 * `List<int>`, and `float`.
 *
 * When list columns are present, depending on the input flag `decompose_lists`, the decomposition
 * can be performed similarly to pure structs but list parent columns are NOT pruned. The list
 * parents are still needed to define the range of elements in the leaf that belong to the same row.
 *
 * For example, if the original table has a column `List<Struct<int, float>>`,
 *
 *    L
 *    |
 *    S
 *   / \
 *  i   f
 *
 * after decomposition, we get two columns
 *
 *  L   L
 *  |   |
 *  S   f
 *  |
 *  i
 *
 * Note that the `decompose_lists` flag should be specified as follow:
 *  - `decompose_lists_column::YES` when preprocessing a table for equality comparison.
 *  - `decompose_lists_column::NO` when preprocessing a table for lexicographic comparison,
 *    since we need to keep all lists columns intact to input into the next preprocessing step.
 *
 * @param table The table whose struct columns to decompose.
 * @param decompose_lists Whether to decompose lists columns
 * @param column_order The per-column order if using output with lexicographic comparison
 * @param null_precedence The per-column null precedence
 * @return A tuple containing a table with all struct columns decomposed, new corresponding column
 *         orders and null precedences and depths of the linearized branches
 */
auto decompose_structs(table_view table,
                       decompose_lists_column decompose_lists,
                       host_span<order const> column_order         = {},
                       host_span<null_order const> null_precedence = {})
{
  auto linked_columns = detail::table_to_linked_columns(table);

  std::vector<column_view> verticalized_columns;
  std::vector<order> new_column_order;
  std::vector<null_order> new_null_precedence;
  std::vector<int> verticalized_col_depths;
  for (size_t col_idx = 0; col_idx < linked_columns.size(); ++col_idx) {
    detail::linked_column_view const* col = linked_columns[col_idx].get();
    if (is_nested(col->type())) {
      // convert and insert
      std::vector<std::vector<detail::linked_column_view const*>> flattened;
      std::function<void(
        detail::linked_column_view const*, std::vector<detail::linked_column_view const*>*, int)>
        recursive_child = [&](detail::linked_column_view const* c,
                              std::vector<detail::linked_column_view const*>* branch,
                              int depth) {
          branch->push_back(c);
          if (decompose_lists == decompose_lists_column::YES && c->type().id() == type_id::LIST) {
            recursive_child(
              c->children[lists_column_view::child_column_index].get(), branch, depth + 1);
          } else if (c->type().id() == type_id::STRUCT) {
            for (size_t child_idx = 0; child_idx < c->children.size(); ++child_idx) {
              // When child_idx == 0, we also cut off the current branch if its first child is a
              // lists column.
              // In such cases, the last column of the current branch will be `Struct<List,...>` and
              // it will be modified to empty struct type `Struct<>` later on.
              if (child_idx > 0 || c->children[0]->type().id() == type_id::LIST) {
                verticalized_col_depths.push_back(depth + 1);
                branch = &flattened.emplace_back();
              }
              recursive_child(c->children[child_idx].get(), branch, depth + 1);
            }
          }
        };
      auto& branch = flattened.emplace_back();
      verticalized_col_depths.push_back(0);
      recursive_child(col, &branch, 0);

      for (auto const& branch : flattened) {
        column_view temp_col = *branch.back();

        // Change `Struct<List,...>` into empty struct type `Struct<>`.
        if (temp_col.type().id() == type_id::STRUCT &&
            (temp_col.num_children() > 0 && temp_col.child(0).type().id() == type_id::LIST)) {
          temp_col = column_view(temp_col.type(),
                                 temp_col.size(),
                                 temp_col.head(),
                                 temp_col.null_mask(),
                                 temp_col.null_count(),
                                 temp_col.offset(),
                                 {});
        }

        for (auto it = branch.crbegin() + 1; it < branch.crend(); ++it) {
          auto const& prev_col = *(*it);
          auto children =
            (prev_col.type().id() == type_id::LIST)
              ? std::vector<column_view>{*prev_col
                                            .children[lists_column_view::offsets_column_index],
                                         temp_col}
              : std::vector<column_view>{temp_col};
          temp_col = column_view(prev_col.type(),
                                 prev_col.size(),
                                 nullptr,
                                 prev_col.null_mask(),
                                 prev_col.null_count(),
                                 prev_col.offset(),
                                 std::move(children));
        }
        // Traverse upward and include any list columns in the ancestors
        for (detail::linked_column_view* parent = branch.front()->parent; parent;
             parent                             = parent->parent) {
          if (parent->type().id() == type_id::LIST) {
            // Include this parent
            temp_col = column_view(
              parent->type(),
              parent->size(),
              nullptr,  // list has no data of its own
              nullptr,  // If we're going through this then nullmask is already in another branch
              0,
              parent->offset(),
              {*parent->children[lists_column_view::offsets_column_index], temp_col});
          } else if (parent->type().id() == type_id::STRUCT) {
            // Replace offset with parent's offset
            temp_col = column_view(temp_col.type(),
                                   parent->size(),
                                   temp_col.head(),
                                   temp_col.null_mask(),
                                   temp_col.null_count(),
                                   parent->offset(),
                                   {temp_col.child_begin(), temp_col.child_end()});
          }
        }
        verticalized_columns.push_back(temp_col);
      }
      if (not column_order.empty()) {
        new_column_order.insert(new_column_order.end(), flattened.size(), column_order[col_idx]);
      }
      if (not null_precedence.empty()) {
        new_null_precedence.insert(
          new_null_precedence.end(), flattened.size(), null_precedence[col_idx]);
      }
    } else {
      verticalized_columns.push_back(*col);
      verticalized_col_depths.push_back(0);
      if (not column_order.empty()) { new_column_order.push_back(column_order[col_idx]); }
      if (not null_precedence.empty()) { new_null_precedence.push_back(null_precedence[col_idx]); }
    }
  }
  return std::make_tuple(table_view(verticalized_columns),
                         std::move(new_column_order),
                         std::move(new_null_precedence),
                         std::move(verticalized_col_depths));
}

/*
 * This helper function generates dremel data for any list-type columns in a
 * table. This data is necessary for lexicographic comparisons.
 */
auto list_lex_preprocess(table_view const& table, rmm::cuda_stream_view stream)
{
  std::vector<detail::dremel_data> dremel_data;
  auto const num_list_columns = std::count_if(
    table.begin(), table.end(), [](auto const& col) { return col.type().id() == type_id::LIST; });
  auto dremel_device_views =
    cudf::detail::make_empty_host_vector<detail::dremel_device_view>(num_list_columns, stream);
  for (auto const& col : table) {
    if (col.type().id() == type_id::LIST) {
      dremel_data.push_back(detail::get_comparator_data(col, {}, false, stream));
      dremel_device_views.push_back(dremel_data.back());
    }
  }
  auto d_dremel_device_views = detail::make_device_uvector(
    dremel_device_views, stream, cudf::get_current_device_resource_ref());
  return std::make_tuple(std::move(dremel_data), std::move(d_dremel_device_views));
}

using column_checker_fn_t = std::function<void(column_view const&)>;

/**
 * @brief Check a table for compatibility with lexicographic comparison
 *
 * Checks whether a given table contains columns of non-relationally comparable types.
 */
void check_lex_compatibility(table_view const& input)
{
  // Basically check if there's any LIST of STRUCT or STRUCT of LIST hiding anywhere in the table
  column_checker_fn_t check_column = [&](column_view const& c) {
    if (c.type().id() == type_id::LIST) {
      auto const& list_col = lists_column_view(c);
      CUDF_EXPECTS(list_col.child().type().id() != type_id::STRUCT,
                   "Cannot lexicographically compare a table with a LIST of STRUCT column");
      check_column(list_col.child());
    } else if (c.type().id() == type_id::STRUCT) {
      for (auto child = c.child_begin(); child < c.child_end(); ++child) {
        CUDF_EXPECTS(child->type().id() != type_id::LIST,
                     "Cannot lexicographically compare a table with a STRUCT of LIST column");
        check_column(*child);
      }
    }
    if (not is_nested(c.type())) {
      CUDF_EXPECTS(is_relationally_comparable(c.type()),
                   "Cannot lexicographic compare a table with a column of type " +
                     cudf::type_to_name(c.type()));
    }
  };
  for (column_view const& c : input) {
    check_column(c);
  }
}

/**
 * @brief Check a table for compatibility with equality comparison
 *
 * Checks whether a given table contains columns of non-equality comparable types.
 */
void check_eq_compatibility(table_view const& input)
{
  column_checker_fn_t check_column = [&](column_view const& c) {
    if (not is_nested(c.type())) {
      CUDF_EXPECTS(
        is_equality_comparable(c.type()),
        "Cannot compare equality for a table with a column of type " + cudf::type_to_name(c.type()),
        std::invalid_argument);
    }
    for (auto child = c.child_begin(); child < c.child_end(); ++child) {
      check_column(*child);
    }
  };
  for (column_view const& c : input) {
    check_column(c);
  }
}

void check_shape_compatibility(table_view const& lhs, table_view const& rhs)
{
  CUDF_EXPECTS(lhs.num_columns() == rhs.num_columns(),
               "Cannot compare tables with different number of columns",
               std::invalid_argument);
  for (size_type i = 0; i < lhs.num_columns(); ++i) {
    CUDF_EXPECTS(column_types_equivalent(lhs.column(i), rhs.column(i)),
                 "Cannot compare tables with different column types",
                 std::invalid_argument);
  }
}

}  // namespace

namespace row {

namespace lexicographic {

namespace {

/**
 * @brief Replace child of the input lists column by a new child column.
 *
 * If the input is not sliced, just replace the input child by the new_child.
 * Otherwise, we have to generate new offsets and replace both the offsets and the child of the
 * input by the new ones. This is because the new child was generated by ranking and always
 * has zero offset, so it cannot replace the input child if it is sliced.
 *
 * The new generated offsets column needs to be returned and kept alive.
 *
 * @param[in] input The input column_view of type LIST
 * @param[in] new_child A new child column to replace the existing child of the input
 * @param[out] out_cols An array to store the new generated offsets (if applicable)
 * @param[in] stream CUDA stream used for device memory operations and kernel launches
 * @param[in] mr Device memory resource used to allocate the returned column
 * @return An output column_view with child replaced
 */
auto replace_child(column_view const& input,
                   column_view const& new_child,
                   std::vector<std::unique_ptr<column>>& out_cols,
                   rmm::cuda_stream_view stream,
                   rmm::device_async_resource_ref mr)
{
  auto const make_output = [&input](auto const& offsets_cv, auto const& child_cv) {
    return column_view{data_type{type_id::LIST},
                       input.size(),
                       nullptr,
                       input.null_mask(),
                       input.null_count(),
                       0,
                       {offsets_cv, child_cv}};
  };

  if (input.offset() == 0) {
    return make_output(input.child(lists_column_view::offsets_column_index), new_child);
  }

  out_cols.emplace_back(
    cudf::lists::detail::get_normalized_offsets(lists_column_view{input}, stream, mr));
  return make_output(out_cols.back()->view(), new_child);
}

/**
 * @brief Compute ranks of the input column.
 *
 * `Dense` rank type must be used for compute ranking of the input for later lexicographic
 * comparison.
 *
 * To understand why, consider: `input = [ [{0, "a"}, {3, "c"}], [{0, "a"}, {2, "b"}] ]`.
 * If first rank is used, `transformed_input = [ [0, 3], [1, 2] ]`. Comparing them will lead
 * to the result row(0) < row(1) which is incorrect.
 * With dense rank, `transformed_input = [ [0, 2], [0, 1] ]`, producing the correct output for
 * lexicographic comparison.
 *
 * In addition, since the input column being ranked is always a nested child column instead of
 * a top-level column, the column order for ranking should be fixed to the same value
 * `order::ASCENDING` in all situations.
 * For example, with the same input above, using column order as `order::ASCENDING` we will have
 * `transformed_input = [ [0, 2], [0, 1] ]`. The output of sorting `transformed_input` will be
 * exactly the same as sorting `input` regardless of the sorting order (ASC or DESC).
 *
 * @param input The input column to compute ranks
 * @param column_null_order The flag indicating how nulls compare to non-null values
 * @param stream CUDA stream used for device memory operations and kernel launches
 * @param mr Device memory resource used to allocate the returned column
 * @return The output rank columns
 */
auto compute_ranks(column_view const& input,
                   null_order column_null_order,
                   rmm::cuda_stream_view stream,
                   rmm::device_async_resource_ref mr)
{
  return cudf::detail::rank(input,
                            rank_method::DENSE,
                            order::ASCENDING,
                            null_policy::EXCLUDE,
                            column_null_order,
                            false /*percentage*/,
                            stream,
                            mr);
}

/**
 * @brief Transform any nested lists-of-structs column into lists-of-integers column.
 *
 * For a lists-of-structs column at any nested level, its child structs column will be replaced by a
 * `size_type` column computed as its ranks.
 *
 * If the input column is not lists-of-structs, or does not contain lists-of-structs at any nested
 * level, the input will be passed through without any changes.
 *
 * @param input The input column to transform
 * @param column_null_order The flag indicating how nulls compare to non-null values
 * @param stream CUDA stream used for device memory operations and kernel launches
 * @param mr Device memory resource used to allocate the returned column(s)
 * @return A pair consisting of new column_view representing the transformed input, along with
 *         an array containing its rank column(s) (of `size_type` type) and possibly new list
 *         offsets generated during the transformation process
 */
std::pair<column_view, std::vector<std::unique_ptr<column>>> transform_lists_of_structs(
  column_view const& input,
  null_order column_null_order,
  rmm::cuda_stream_view stream,
  rmm::device_async_resource_ref mr)
{
  std::vector<std::unique_ptr<column>> out_cols;

  if (input.type().id() == type_id::LIST) {
    auto const child = cudf::lists_column_view{input}.get_sliced_child(stream);

    // Found a lists-of-structs column.
    if (child.type().id() == type_id::STRUCT) {
      out_cols.emplace_back(compute_ranks(child, column_null_order, stream, mr));
      return {replace_child(input, out_cols.back()->view(), out_cols, stream, mr),
              std::move(out_cols)};
    }
    // Found a lists-of-lists column.
    else if (child.type().id() == type_id::LIST) {
      // Recursively call transformation on the child column.
      auto [new_child, out_cols_child] =
        transform_lists_of_structs(child, column_null_order, stream, mr);

      // Only transform the current column if its child has been transformed.
      if (out_cols_child.size() > 0) {
        out_cols.insert(out_cols.end(),
                        std::make_move_iterator(out_cols_child.begin()),
                        std::make_move_iterator(out_cols_child.end()));
        return {replace_child(input, new_child, out_cols, stream, mr), std::move(out_cols)};
      }
      // else: child was not transformed so input is also not transformed.
    }
    // else: child is not STRUCT or LIST: no transformation.
  }
  // else: lhs.type().id() != type_id::LIST.
  // In such situations, lhs.type().id() can still be type_id::STRUCT. However, any
  // structs-of-lists should be decomposed into empty struct type `Struct<>` before being
  // processed by this function so we do nothing here.

  // Passthrough: nothing changed.
  return {input, std::move(out_cols)};
}

/**
 * @brief Transform any nested lists-of-structs column into lists-of-integers column.
 *
 * For a lists-of-structs column at any nested level, its child structs column will be replaced by a
 * `size_type` column computed as its ranks. In addition, equivalent child columns of both input
 * columns (i.e., child columns at the same order, same nested level) will be combined and
 * ranked together.
 *
 * If the input columns are not lists-of-structs, or do not contain lists-of-structs at any nested
 * level, there will not be any changes.
 *
 * @param lhs The input lhs column to transform
 * @param rhs The input rhs column to transform
 * @param column_null_order The flag indicating how nulls compare to non-null values
 * @param stream CUDA stream used for device memory operations and kernel launches
 * @param mr Device memory resource used to allocate the returned column(s)
 * @return A tuple consisting of new column_view(s) representing the transformed input, along with
 *         their rank column(s) (of `size_type` type) and possibly new list offsets generated
 *         during the transformation process
 */
std::tuple<column_view,
           column_view,
           std::vector<std::unique_ptr<column>>,
           std::vector<std::unique_ptr<column>>>
transform_lists_of_structs(column_view const& lhs,
                           column_view const& rhs,
                           null_order column_null_order,
                           rmm::cuda_stream_view stream,
                           rmm::device_async_resource_ref mr)
{
  std::vector<std::unique_ptr<column>> out_cols_lhs;
  std::vector<std::unique_ptr<column>> out_cols_rhs;

  auto const make_output = [&](auto const& new_child_lhs, auto const& new_child_rhs) {
    return std::tuple{replace_child(lhs, new_child_lhs, out_cols_lhs, stream, mr),
                      replace_child(rhs, new_child_rhs, out_cols_rhs, stream, mr),
                      std::move(out_cols_lhs),
                      std::move(out_cols_rhs)};
  };

  if (lhs.type().id() == type_id::LIST) {
    auto const child_lhs = cudf::lists_column_view{lhs}.get_sliced_child(stream);
    auto const child_rhs = cudf::lists_column_view{rhs}.get_sliced_child(stream);

    // Found a lists-of-structs column.
    if (child_lhs.type().id() == type_id::STRUCT) {
      auto const concatenated_children =
        cudf::detail::concatenate(std::vector<column_view>{child_lhs, child_rhs},
                                  stream,
                                  cudf::get_current_device_resource_ref());

      auto const ranks        = compute_ranks(concatenated_children->view(),
                                       column_null_order,
                                       stream,
                                       cudf::get_current_device_resource_ref());
      auto const ranks_slices = cudf::detail::slice(
        ranks->view(),
        {0, child_lhs.size(), child_lhs.size(), child_lhs.size() + child_rhs.size()},
        stream);

      out_cols_lhs.emplace_back(std::make_unique<column>(ranks_slices.front(), stream, mr));
      out_cols_rhs.emplace_back(std::make_unique<column>(ranks_slices.back(), stream, mr));

      return make_output(out_cols_lhs.back()->view(), out_cols_rhs.back()->view());

    }
    // Found a lists-of-lists column.
    else if (child_lhs.type().id() == type_id::LIST) {
      // Recursively call transformation on the child column.
      auto [new_child_lhs, new_child_rhs, out_cols_child_lhs, out_cols_child_rhs] =
        transform_lists_of_structs(child_lhs, child_rhs, column_null_order, stream, mr);

      // Only transform the current pair of columns if their children have been transformed.
      if (out_cols_child_lhs.size() > 0 || out_cols_child_rhs.size() > 0) {
        out_cols_lhs.insert(out_cols_lhs.end(),
                            std::make_move_iterator(out_cols_child_lhs.begin()),
                            std::make_move_iterator(out_cols_child_lhs.end()));
        out_cols_rhs.insert(out_cols_rhs.end(),
                            std::make_move_iterator(out_cols_child_rhs.begin()),
                            std::make_move_iterator(out_cols_child_rhs.end()));

        return make_output(new_child_lhs, new_child_rhs);
      }
    }
    // else: child is not STRUCT or LIST: just go to the end of this function, no transformation.
  }
  // else: lhs.type().id() != type_id::LIST.
  // In such situations, lhs.type().id() can still be type_id::STRUCT. However, any
  // structs-of-lists should be decomposed into empty struct type `Struct<>` before being
  // processed by this function so we do nothing here.

  // Passthrough: nothing changed.
  return {lhs, rhs, std::move(out_cols_lhs), std::move(out_cols_rhs)};
}

}  // namespace

std::shared_ptr<preprocessed_table> preprocessed_table::create(
  table_view const& preprocessed_input,
  std::vector<int>&& verticalized_col_depths,
  std::vector<std::unique_ptr<column>>&& transformed_columns,
  host_span<order const> column_order,
  host_span<null_order const> null_precedence,
  bool has_ranked_children,
  rmm::cuda_stream_view stream)
{
  check_lex_compatibility(preprocessed_input);

  auto d_table        = table_device_view::create(preprocessed_input, stream);
  auto d_column_order = detail::make_device_uvector_async(
    column_order, stream, cudf::get_current_device_resource_ref());
  auto d_null_precedence = detail::make_device_uvector_async(
    null_precedence, stream, cudf::get_current_device_resource_ref());
  auto d_depths = detail::make_device_uvector_async(
    verticalized_col_depths, stream, cudf::get_current_device_resource_ref());

  if (detail::has_nested_columns(preprocessed_input)) {
    auto [dremel_data, d_dremel_device_view] = list_lex_preprocess(preprocessed_input, stream);
    return std::shared_ptr<preprocessed_table>(
      new preprocessed_table(std::move(d_table),
                             std::move(d_column_order),
                             std::move(d_null_precedence),
                             std::move(d_depths),
                             std::move(dremel_data),
                             std::move(d_dremel_device_view),
                             std::move(transformed_columns),
                             has_ranked_children));
  } else {
    return std::shared_ptr<preprocessed_table>(
      new preprocessed_table(std::move(d_table),
                             std::move(d_column_order),
                             std::move(d_null_precedence),
                             std::move(d_depths),
                             std::move(transformed_columns),
                             has_ranked_children));
  }
}

std::shared_ptr<preprocessed_table> preprocessed_table::create(
  table_view const& input,
  host_span<order const> column_order,
  host_span<null_order const> null_precedence,
  rmm::cuda_stream_view stream)
{
  auto [decomposed_input, new_column_order, new_null_precedence, verticalized_col_depths] =
    decompose_structs(input, decompose_lists_column::NO, column_order, null_precedence);

  // Transform any (nested) lists-of-structs column into lists-of-integers column.
  std::vector<std::unique_ptr<column>> transformed_columns;
  auto const transformed_input =
    [&, &decomposed_input = decomposed_input, &new_null_precedence = new_null_precedence] {
      std::vector<column_view> transformed_cvs;

      for (size_type col_idx = 0; col_idx < decomposed_input.num_columns(); ++col_idx) {
        auto const& lhs_col = decomposed_input.column(col_idx);

        auto [transformed, curr_out_cols] = transform_lists_of_structs(
          lhs_col,
          null_precedence.empty() ? null_order::BEFORE : new_null_precedence[col_idx],
          stream,
          cudf::get_current_device_resource_ref());

        transformed_cvs.emplace_back(std::move(transformed));
        transformed_columns.insert(transformed_columns.end(),
                                   std::make_move_iterator(curr_out_cols.begin()),
                                   std::make_move_iterator(curr_out_cols.end()));
      }

      return table_view{transformed_cvs};
    }();

  auto const has_ranked_children = !transformed_columns.empty();
  return create(transformed_input,
                std::move(verticalized_col_depths),
                std::move(transformed_columns),
                new_column_order,
                new_null_precedence,
                has_ranked_children,
                stream);
}

std::pair<std::shared_ptr<preprocessed_table>, std::shared_ptr<preprocessed_table>>
preprocessed_table::create(table_view const& lhs,
                           table_view const& rhs,
                           host_span<order const> column_order,
                           host_span<null_order const> null_precedence,
                           rmm::cuda_stream_view stream)
{
  check_shape_compatibility(lhs, rhs);

  auto [decomposed_lhs,
        new_column_order_lhs,
        new_null_precedence_lhs,
        verticalized_col_depths_lhs] =
    decompose_structs(lhs, decompose_lists_column::NO, column_order, null_precedence);

  // Unused variables are new column order and null order for rhs, which are the same as for lhs
  // so we don't need them.
  [[maybe_unused]] auto [decomposed_rhs, unused0, unused1, verticalized_col_depths_rhs] =
    decompose_structs(rhs, decompose_lists_column::NO, column_order, null_precedence);

  // Transform any (nested) lists-of-structs column into lists-of-integers column.
  std::vector<std::unique_ptr<column>> transformed_columns_lhs;
  std::vector<std::unique_ptr<column>> transformed_columns_rhs;
  auto const [transformed_lhs,
              transformed_rhs] = [&,
                                  &decomposed_lhs          = decomposed_lhs,
                                  &decomposed_rhs          = decomposed_rhs,
                                  &new_null_precedence_lhs = new_null_precedence_lhs] {
    std::vector<column_view> transformed_lhs_cvs;
    std::vector<column_view> transformed_rhs_cvs;

    for (size_type col_idx = 0; col_idx < decomposed_lhs.num_columns(); ++col_idx) {
      auto const& lhs_col = decomposed_lhs.column(col_idx);
      auto const& rhs_col = decomposed_rhs.column(col_idx);

      auto [transformed_lhs, transformed_rhs, curr_out_cols_lhs, curr_out_cols_rhs] =
        transform_lists_of_structs(
          lhs_col,
          rhs_col,
          null_precedence.empty() ? null_order::BEFORE : new_null_precedence_lhs[col_idx],
          stream,
          cudf::get_current_device_resource_ref());

      transformed_lhs_cvs.emplace_back(std::move(transformed_lhs));
      transformed_rhs_cvs.emplace_back(std::move(transformed_rhs));
      transformed_columns_lhs.insert(transformed_columns_lhs.end(),
                                     std::make_move_iterator(curr_out_cols_lhs.begin()),
                                     std::make_move_iterator(curr_out_cols_lhs.end()));
      transformed_columns_rhs.insert(transformed_columns_rhs.end(),
                                     std::make_move_iterator(curr_out_cols_rhs.begin()),
                                     std::make_move_iterator(curr_out_cols_rhs.end()));
    }

    return std::pair{table_view{transformed_lhs_cvs}, table_view{transformed_rhs_cvs}};
  }();

  // This should be the same for both lhs and rhs but not all the time, such as when one table
  // has 0 rows while the other has >0 rows. So we check separately for each of them.
  auto const has_ranked_children_lhs = !transformed_columns_lhs.empty();
  auto const has_ranked_children_rhs = !transformed_columns_rhs.empty();

  return {create(transformed_lhs,
                 std::move(verticalized_col_depths_lhs),
                 std::move(transformed_columns_lhs),
                 new_column_order_lhs,
                 new_null_precedence_lhs,
                 has_ranked_children_lhs,
                 stream),
          create(transformed_rhs,
                 std::move(verticalized_col_depths_rhs),
                 std::move(transformed_columns_rhs),
                 new_column_order_lhs,
                 new_null_precedence_lhs,
                 has_ranked_children_rhs,
                 stream)};
}

preprocessed_table::preprocessed_table(
  table_device_view_owner&& table,
  rmm::device_uvector<order>&& column_order,
  rmm::device_uvector<null_order>&& null_precedence,
  rmm::device_uvector<size_type>&& depths,
  std::vector<detail::dremel_data>&& dremel_data,
  rmm::device_uvector<detail::dremel_device_view>&& dremel_device_views,
  std::vector<std::unique_ptr<column>>&& transformed_columns,
  bool has_ranked_children)
  : _t(std::move(table)),
    _column_order(std::move(column_order)),
    _null_precedence(std::move(null_precedence)),
    _depths(std::move(depths)),
    _dremel_data(std::move(dremel_data)),
    _dremel_device_views(std::move(dremel_device_views)),
    _transformed_columns(std::move(transformed_columns)),
    _has_ranked_children(has_ranked_children)
{
}

preprocessed_table::preprocessed_table(table_device_view_owner&& table,
                                       rmm::device_uvector<order>&& column_order,
                                       rmm::device_uvector<null_order>&& null_precedence,
                                       rmm::device_uvector<size_type>&& depths,
                                       std::vector<std::unique_ptr<column>>&& transformed_columns,
                                       bool has_ranked_children)
  : _t(std::move(table)),
    _column_order(std::move(column_order)),
    _null_precedence(std::move(null_precedence)),
    _depths(std::move(depths)),
    _dremel_data{},
    _dremel_device_views{},
    _transformed_columns(std::move(transformed_columns)),
    _has_ranked_children(has_ranked_children)
{
}

two_table_comparator::two_table_comparator(table_view const& left,
                                           table_view const& right,
                                           host_span<order const> column_order,
                                           host_span<null_order const> null_precedence,
                                           rmm::cuda_stream_view stream)
{
  std::tie(d_left_table, d_right_table) =
    preprocessed_table::create(left, right, column_order, null_precedence, stream);
}

}  // namespace lexicographic

namespace equality {

namespace {

constexpr std::size_t reservation_scan_chunk_rows = 4096;

std::size_t reservation_checked_add(std::size_t lhs, std::size_t rhs)
{
  CUDF_EXPECTS(lhs <= std::numeric_limits<std::size_t>::max() - rhs,
               "row operator preprocessing reservation size overflow",
               std::overflow_error);
  return lhs + rhs;
}

std::size_t reservation_checked_mul(std::size_t lhs, std::size_t rhs)
{
  CUDF_EXPECTS(rhs == 0 || lhs <= std::numeric_limits<std::size_t>::max() / rhs,
               "row operator preprocessing reservation size overflow",
               std::overflow_error);
  return lhs * rhs;
}

// Whether the dirty-row gate reads the stored view metadata or the exact count produced by
// null push-down. This mirrors `column_view::has_nulls()` on the view that
// `has_nonempty_nulls` observes at each recursion level. FORCE_CLEAN mirrors the mask
// adoption case, where the pushed child view reports zero nulls.
enum class simulated_null_count { STORED, EXACT, FORCE_CLEAN };

// A column as seen by null push-down: original storage plus the masks ANDed into its
// validity. All masks use absolute bit addressing; row i is addressed at `offset + i`.
struct simulated_column {
  column_view storage;
  std::vector<bitmask_type const*> validity_masks;
  simulated_null_count null_count_rule;
  size_type offset;
  size_type size;
  std::vector<simulated_column> children;  // STRUCT columns: null-pushed or raw children
};

bool simulated_dirty_gate(simulated_column const& node)
{
  if (node.validity_masks.empty() || node.null_count_rule == simulated_null_count::FORCE_CLEAN) {
    return false;
  }
  return node.null_count_rule == simulated_null_count::EXACT || node.storage.null_count() > 0;
}

// Scans rows [row_begin, row_end) of a string/list node in bounded chunks, invoking
// `fn(valid, offset_begin, offset_end)` per row. Reads device metadata only; allocates nothing.
template <typename Offset, typename RowFn>
void scan_variable_width_rows(column_view const& offsets_child,
                              std::vector<bitmask_type const*> const& masks,
                              std::size_t row_begin,
                              std::size_t row_end,
                              rmm::cuda_stream_view stream,
                              RowFn&& fn)
{
  auto const* const offsets  = offsets_child.head<Offset>();
  constexpr auto bits_per_word = sizeof(bitmask_type) * CHAR_BIT;
  std::array<Offset, reservation_scan_chunk_rows + 1> host_offsets{};
  std::array<bitmask_type, reservation_scan_chunk_rows / bits_per_word + 2> host_words{};
  std::array<bitmask_type, reservation_scan_chunk_rows / bits_per_word + 2> mask_words{};

  for (auto begin = row_begin; begin < row_end;) {
    auto const rows       = std::min(reservation_scan_chunk_rows, row_end - begin);
    auto const first_word = begin / bits_per_word;
    auto const word_count = (begin + rows - 1) / bits_per_word - first_word + 1;
    CUDF_CUDA_TRY(cudaMemcpyAsync(host_offsets.data(),
                                  offsets + begin,
                                  (rows + 1) * sizeof(Offset),
                                  cudaMemcpyDeviceToHost,
                                  stream.value()));
    bool first_mask = true;
    for (auto const* mask : masks) {
      CUDF_CUDA_TRY(cudaMemcpyAsync(mask_words.data(),
                                    mask + first_word,
                                    word_count * sizeof(bitmask_type),
                                    cudaMemcpyDeviceToHost,
                                    stream.value()));
      stream.synchronize();
      for (std::size_t word = 0; word < word_count; ++word) {
        host_words[word] = first_mask ? mask_words[word] : (host_words[word] & mask_words[word]);
      }
      first_mask = false;
    }
    stream.synchronize();
    for (std::size_t row = 0; row < rows; ++row) {
      auto const valid = masks.empty() ||
                         cudf::bit_is_set(host_words.data(),
                                          static_cast<size_type>(begin + row -
                                                                 first_word * bits_per_word));
      auto const offset_begin = static_cast<int64_t>(host_offsets[row]);
      auto const offset_end   = static_cast<int64_t>(host_offsets[row + 1]);
      CUDF_EXPECTS(offset_begin >= 0 && offset_end >= offset_begin,
                   "invalid offsets while sizing row operator preprocessing",
                   std::invalid_argument);
      fn(valid, offset_begin, offset_end);
    }
    begin += rows;
  }
}

template <typename RowFn>
void scan_node_rows(simulated_column const& node,
                    std::size_t local_begin,
                    std::size_t local_end,
                    rmm::cuda_stream_view stream,
                    RowFn&& fn)
{
  auto const type = node.storage.type().id();
  auto const offsets_child =
    type == type_id::STRING
      ? strings_column_view{node.storage}.offsets()
      : lists_column_view{node.storage}.offsets();
  auto const abs_begin = static_cast<std::size_t>(node.offset) + local_begin;
  auto const abs_end   = static_cast<std::size_t>(node.offset) + local_end;
  if (type == type_id::STRING && offsets_child.type().id() == type_id::INT64) {
    scan_variable_width_rows<int64_t>(
      offsets_child, node.validity_masks, abs_begin, abs_end, stream, fn);
  } else {
    CUDF_EXPECTS(offsets_child.type().id() == type_id::INT32,
                 "string/list offsets must use INT32 or INT64",
                 cudf::data_type_error);
    scan_variable_width_rows<int32_t>(
      offsets_child, node.validity_masks, abs_begin, abs_end, stream, fn);
  }
}

// Returns true if `mask` has an unset bit in [bit_begin, bit_end), reading in bounded chunks.
bool mask_has_unset_bits(bitmask_type const* mask,
                         std::size_t bit_begin,
                         std::size_t bit_end,
                         rmm::cuda_stream_view stream)
{
  if (mask == nullptr || bit_begin >= bit_end) { return false; }
  constexpr auto bits_per_word = sizeof(bitmask_type) * CHAR_BIT;
  std::array<bitmask_type, reservation_scan_chunk_rows / bits_per_word + 2> host_words{};
  for (auto begin = bit_begin; begin < bit_end;) {
    auto const bits       = std::min(reservation_scan_chunk_rows, bit_end - begin);
    auto const first_word = begin / bits_per_word;
    auto const word_count = (begin + bits - 1) / bits_per_word - first_word + 1;
    CUDF_CUDA_TRY(cudaMemcpyAsync(host_words.data(),
                                  mask + first_word,
                                  word_count * sizeof(bitmask_type),
                                  cudaMemcpyDeviceToHost,
                                  stream.value()));
    stream.synchronize();
    for (std::size_t bit = 0; bit < bits; ++bit) {
      if (!cudf::bit_is_set(host_words.data(),
                            static_cast<size_type>(begin + bit - first_word * bits_per_word))) {
        return true;
      }
    }
    begin += bits;
  }
  return false;
}

template <typename Offset>
Offset read_offset_value(column_view const& offsets_child,
                         std::size_t position,
                         rmm::cuda_stream_view stream)
{
  Offset value{};
  CUDF_CUDA_TRY(cudaMemcpyAsync(&value,
                                offsets_child.head<Offset>() + position,
                                sizeof(Offset),
                                cudaMemcpyDeviceToHost,
                                stream.value()));
  stream.synchronize();
  return value;
}

// A child untouched by null push-down (list subtrees are not pushed): the raw child view with
// its own stored null metadata.
simulated_column unpushed_child(column_view const& child)
{
  auto masks = std::vector<bitmask_type const*>{};
  if (child.nullable()) { masks.push_back(child.null_mask()); }
  auto node = simulated_column{
    child, std::move(masks), simulated_null_count::STORED, child.offset(), child.size(), {}};
  if (child.type().id() == type_id::STRUCT) {
    for (auto it = child.child_begin(); it != child.child_end(); ++it) {
      node.children.push_back(unpushed_child(*it));
    }
  }
  return node;
}

// The element child of a list node, as seen by the preprocessing recursion.
simulated_column list_element_child(simulated_column const& list_node)
{
  return unpushed_child(list_node.storage.child(lists_column_view::child_column_index));
}

// Mirrors cudf::detail::has_nonempty_nulls on the null-pushed view hierarchy.
bool simulated_has_nonempty_nulls(simulated_column const& node, rmm::cuda_stream_view stream)
{
  auto const type = node.storage.type().id();
  if (type != type_id::STRING && type != type_id::LIST && type != type_id::STRUCT) {
    return false;
  }
  if (type == type_id::STRING || type == type_id::LIST) {
    if (simulated_dirty_gate(node)) {
      auto dirty = false;
      scan_node_rows(node,
                     0,
                     static_cast<std::size_t>(node.size),
                     stream,
                     [&dirty](bool valid, int64_t offset_begin, int64_t offset_end) {
                       dirty = dirty || (!valid && offset_end > offset_begin);
                     });
      if (dirty) { return true; }
    }
    if (type == type_id::LIST) {
      return simulated_has_nonempty_nulls(list_element_child(node), stream);
    }
    return false;
  }
  return std::any_of(node.children.begin(), node.children.end(), [stream](auto const& child) {
    return simulated_has_nonempty_nulls(child, stream);
  });
}

// Mirrors structs::detail::push_down_nulls_no_sanitize: simulates the null-mask push-down for
// struct columns and accumulates the retained mask bytes into `mask_bytes`.
simulated_column simulate_pushed_column(column_view const& col,
                                        std::vector<bitmask_type const*> ancestor_masks,
                                        size_type offset,
                                        size_type size,
                                        std::size_t& mask_bytes)
{
  auto masks = std::move(ancestor_masks);
  if (col.nullable()) { masks.push_back(col.null_mask()); }
  auto node = simulated_column{
    col, std::move(masks), simulated_null_count::EXACT, offset, size, {}};
  if (col.type().id() != type_id::STRUCT) { return node; }

  for (auto child_it = col.child_begin(); child_it != col.child_end(); ++child_it) {
    auto const& child = *child_it;
    // The pushed child shares the pushed struct's offset and size; a nullable child of a
    // nullable struct gets a fresh ANDed mask sized on the struct's extent.
    if (!node.validity_masks.empty() && child.nullable()) {
      mask_bytes = reservation_checked_add(
        mask_bytes, cudf::bitmask_allocation_size_bytes(offset + size));
    }
    if (child.type().id() == type_id::STRUCT) {
      node.children.push_back(
        simulate_pushed_column(child, node.validity_masks, offset, size, mask_bytes));
    } else {
      auto child_masks = node.validity_masks;
      if (child.nullable()) { child_masks.push_back(child.null_mask()); }
      auto const child_rule = node.validity_masks.empty() || child.nullable()
                                ? simulated_null_count::EXACT
                                : simulated_null_count::FORCE_CLEAN;
      node.children.push_back(
        simulated_column{child, std::move(child_masks), child_rule, offset, size, {}});
    }
  }
  return node;
}

// Accumulates the exact identity-gather footprint of a null-pushed column, mirroring
// cudf::detail::purge_nonempty_nulls. `rows` counts selected rows and `payload` counts valid
// string bytes; list element children recurse over maximal runs of selected elements.
struct purge_accumulator {
  simulated_column node;
  std::int64_t rows = 0;
  std::int64_t payload = 0;
  bool mask_retained = false;
  std::size_t full_begin = 0;  // full local row range backing this node; for list children it
  std::size_t full_end = 0;    // is the span the list gather masks are computed over
  std::vector<purge_accumulator> children;  // STRUCT: per child; LIST: element child (lazy)
};

void accumulate_purged_rows(purge_accumulator& acc,
                            std::size_t local_begin,
                            std::size_t local_end,
                            rmm::cuda_stream_view stream);

purge_accumulator make_purge_accumulator(simulated_column node,
                                         std::size_t full_begin,
                                         std::size_t full_end)
{
  auto acc          = purge_accumulator{std::move(node)};
  acc.full_begin    = full_begin;
  acc.full_end      = full_end;
  acc.mask_retained = !acc.node.validity_masks.empty();
  if (acc.node.storage.type().id() == type_id::STRUCT) {
    for (auto& child : acc.node.children) {
      acc.children.push_back(make_purge_accumulator(child, full_begin, full_end));
    }
  }
  return acc;
}

// Creates the accumulator for the element child of `list_acc`. A list gather drops the child's
// null mask unless the child has nulls over the parent's full element span, so the mask gate is
// resolved against that span rather than the selected elements.
purge_accumulator make_list_element_accumulator(purge_accumulator const& list_acc,
                                                rmm::cuda_stream_view stream)
{
  auto const& parent = list_acc.node;
  auto const offsets_child = lists_column_view{parent.storage}.offsets();
  auto const base          = static_cast<std::size_t>(parent.offset);
  auto const span_begin = static_cast<std::size_t>(
    read_offset_value<int32_t>(offsets_child, base + list_acc.full_begin, stream));
  auto const span_end = static_cast<std::size_t>(
    read_offset_value<int32_t>(offsets_child, base + list_acc.full_end, stream));
  auto acc           = make_purge_accumulator(list_element_child(parent), span_begin, span_end);
  acc.mask_retained = std::any_of(
    acc.node.validity_masks.begin(),
    acc.node.validity_masks.end(),
    [&](bitmask_type const* mask) {
      return mask_has_unset_bits(mask,
                                 static_cast<std::size_t>(acc.node.offset) + span_begin,
                                 static_cast<std::size_t>(acc.node.offset) + span_end,
                                 stream);
    });
  return acc;
}

void accumulate_purged_rows(purge_accumulator& acc,
                            std::size_t local_begin,
                            std::size_t local_end,
                            rmm::cuda_stream_view stream)
{
  if (local_begin >= local_end) { return; }
  auto const type = acc.node.storage.type().id();
  acc.rows += static_cast<std::int64_t>(local_end - local_begin);
  if (type == type_id::STRUCT) {
    for (auto& child : acc.children) {
      accumulate_purged_rows(child, local_begin, local_end, stream);
    }
    return;
  }
  if (type != type_id::STRING && type != type_id::LIST) { return; }

  auto run_open  = false;
  std::size_t run_begin = 0;
  std::size_t run_end   = 0;
  auto const flush_run  = [&] {
    if (!run_open) { return; }
    if (acc.children.empty()) {
      acc.children.push_back(make_list_element_accumulator(acc, stream));
    }
    accumulate_purged_rows(acc.children.front(), run_begin, run_end, stream);
    run_open = false;
  };
  scan_node_rows(
    acc.node, local_begin, local_end, stream, [&](bool valid, int64_t offset_begin, int64_t offset_end) {
      if (valid) {
        acc.payload += offset_end - offset_begin;
        if (type == type_id::LIST) {
          if (run_open && static_cast<std::size_t>(offset_begin) == run_end) {
            run_end = static_cast<std::size_t>(offset_end);
          } else {
            flush_run();
            run_begin = static_cast<std::size_t>(offset_begin);
            run_end   = static_cast<std::size_t>(offset_end);
            run_open  = true;
          }
        }
      } else if (type == type_id::LIST) {
        flush_run();
      }
    });
  flush_run();
}

std::size_t finalize_purged_column(purge_accumulator const& acc)
{
  if (acc.rows == 0) { return 0; }
  auto const rows  = static_cast<std::size_t>(acc.rows);
  auto const bytes = acc.mask_retained ? cudf::bitmask_allocation_size_bytes(acc.rows) : 0;
  auto const type  = acc.node.storage.type().id();
  if (type == type_id::STRING) {
    auto const offset_width =
      acc.payload >= cudf::strings::get_offset64_threshold() ? sizeof(int64_t) : sizeof(int32_t);
    return reservation_checked_add(
      bytes,
      reservation_checked_add(reservation_checked_mul(rows + 1, offset_width),
                              static_cast<std::size_t>(acc.payload)));
  }
  if (type == type_id::LIST) {
    auto const child_bytes = acc.children.empty() ? 0 : finalize_purged_column(acc.children.front());
    return reservation_checked_add(
      bytes, reservation_checked_add(reservation_checked_mul(rows + 1, sizeof(int32_t)), child_bytes));
  }
  if (type == type_id::STRUCT) {
    auto total = bytes;
    for (auto const& child : acc.children) {
      total = reservation_checked_add(total, finalize_purged_column(child));
    }
    return total;
  }
  return reservation_checked_add(
    bytes,
    reservation_checked_mul(rows, cudf::size_of(acc.node.storage.type())));
}

std::size_t retained_preprocessing_reservation_size(column_view const& col,
                                                    rmm::cuda_stream_view stream)
{
  auto mask_bytes = std::size_t{0};
  auto root       = [&] {
    if (col.type().id() == type_id::STRUCT) {
      return simulate_pushed_column(col, {}, col.offset(), col.size(), mask_bytes);
    }
    auto masks = std::vector<bitmask_type const*>{};
    if (col.nullable()) { masks.push_back(col.null_mask()); }
    return simulated_column{
      col, std::move(masks), simulated_null_count::STORED, col.offset(), col.size(), {}};
  }();
  if (!simulated_has_nonempty_nulls(root, stream)) { return mask_bytes; }

  auto acc = make_purge_accumulator(root, 0, static_cast<std::size_t>(root.size));
  accumulate_purged_rows(acc, 0, static_cast<std::size_t>(root.size), stream);
  return finalize_purged_column(acc);
}

}  // namespace

std::shared_ptr<preprocessed_table> preprocessed_table::create(table_view const& t,
                                                               rmm::cuda_stream_view stream,
                                                               rmm::device_async_resource_ref mr)
{
  check_eq_compatibility(t);

  auto [null_pushed_table, nullable_data] =
    structs::detail::push_down_nulls(t, stream, mr);
  auto struct_offset_removed_table = remove_struct_child_offsets(null_pushed_table);
  auto verticalized_t =
    std::get<0>(decompose_structs(struct_offset_removed_table, decompose_lists_column::YES));

  auto d_t = table_device_view_owner(table_device_view::create(verticalized_t, stream, mr));
  return std::shared_ptr<preprocessed_table>(new preprocessed_table(
    std::move(d_t), std::move(nullable_data.new_null_masks), std::move(nullable_data.new_columns)));
}

std::size_t preprocessed_table::create_reservation_size(table_view const& t,
                                                        rmm::cuda_stream_view stream)
{
  check_eq_compatibility(t);

  // The verticalized schema is a host-side function of the input schema: null push-down only
  // rewrites masks, and sanitation replaces a column with an identical-schema copy.
  auto const struct_offset_removed_table = remove_struct_child_offsets(t);
  auto const verticalized_t =
    std::get<0>(decompose_structs(struct_offset_removed_table, decompose_lists_column::YES));
  auto bytes = std::accumulate(verticalized_t.begin(),
                               verticalized_t.end(),
                               std::size_t{alignof(column_device_view) - 1},
                               [](std::size_t init, column_view const& col) {
                                 return reservation_checked_add(init, column_device_view::extent(col));
                               });
  for (auto const& col : t) {
    bytes = reservation_checked_add(bytes, retained_preprocessing_reservation_size(col, stream));
  }
  return bytes;
}

two_table_comparator::two_table_comparator(table_view const& left,
                                           table_view const& right,
                                           rmm::cuda_stream_view stream)
  : d_left_table{preprocessed_table::create(left, stream)},
    d_right_table{preprocessed_table::create(right, stream)}
{
  check_shape_compatibility(left, right);
}

two_table_comparator::two_table_comparator(std::shared_ptr<preprocessed_table> left,
                                           std::shared_ptr<preprocessed_table> right)
  : d_left_table{std::move(left)}, d_right_table{std::move(right)}
{
  CUDF_EXPECTS(d_left_table->_t->num_columns() == d_right_table->_t->num_columns(),
               "Cannot compare tables with different number of columns",
               std::invalid_argument);
}

}  // namespace equality

}  // namespace row
}  // namespace detail
}  // namespace cudf
